import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export const LANGUAGES = [
  { code: "en", native: "English",   label: "English"   },
  { code: "hi", native: "हिन्दी",    label: "Hindi"     },
  { code: "mr", native: "मराठी",     label: "Marathi"   },
  { code: "pa", native: "ਪੰਜਾਬੀ",   label: "Punjabi"   },
  { code: "gu", native: "ગુજરાતી",  label: "Gujarati"  },
  { code: "bn", native: "বাংলা",    label: "Bengali"   },
  { code: "ta", native: "தமிழ்",    label: "Tamil"     },
  { code: "te", native: "తెలుగు",   label: "Telugu"    },
  { code: "kn", native: "ಕನ್ನಡ",    label: "Kannada"   },
  { code: "ml", native: "മലയാളം",   label: "Malayalam" },
  { code: "ur", native: "اردو",      label: "Urdu"      },
  { code: "or", native: "ଓଡ଼ିଆ",    label: "Odia"      },
];

// Core UI translations — extend as needed
const translations: Record<string, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    newAnalysis: "New Analysis",
    history: "History",
    market: "Market",
    coldStorage: "Cold Storage",
    weather: "Weather",
    govSchemes: "Gov Schemes",
    profile: "Profile",
    settings: "Settings",
    namaste: "Namaste",
    todayLook: "Here's a quick look at your farm today.",
    temperature: "Temperature",
    humidity: "Humidity",
    rain: "Rain (48h)",
    spoilageAlert: "Spoilage Alert",
    activeAnalyses: "Active Analyses",
    priceTrend: "Price Trend",
    recentAnalyses: "Recent Analyses",
    runAnalysis: "Run an analysis to see forecasts",
    startFirst: "Start your first analysis →",
    selectLanguage: "Select Language",
    loading: "Loading...",
    viewAll: "View all",
    logout: "Logout",
    friday: "Friday",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    newAnalysis: "नया विश्लेषण",
    history: "इतिहास",
    market: "बाज़ार",
    coldStorage: "शीत भंडार",
    weather: "मौसम",
    govSchemes: "सरकारी योजनाएं",
    profile: "प्रोफ़ाइल",
    settings: "सेटिंग्स",
    namaste: "नमस्ते",
    todayLook: "आज आपके खेत की त्वरित जानकारी।",
    temperature: "तापमान",
    humidity: "आर्द्रता",
    rain: "वर्षा (48घं)",
    spoilageAlert: "खराबी चेतावनी",
    activeAnalyses: "सक्रिय विश्लेषण",
    priceTrend: "मूल्य प्रवृत्ति",
    recentAnalyses: "हाल के विश्लेषण",
    runAnalysis: "पूर्वानुमान देखने के लिए विश्लेषण करें",
    startFirst: "पहला विश्लेषण शुरू करें →",
    selectLanguage: "भाषा चुनें",
    loading: "लोड हो रहा है...",
    viewAll: "सभी देखें",
    logout: "लॉग आउट",
    friday: "शुक्रवार",
  },
  mr: {
    dashboard: "डॅशबोर्ड",
    newAnalysis: "नवीन विश्लेषण",
    history: "इतिहास",
    market: "बाजार",
    coldStorage: "शीतगृह",
    weather: "हवामान",
    govSchemes: "सरकारी योजना",
    profile: "प्रोफाइल",
    settings: "सेटिंग्ज",
    namaste: "नमस्कार",
    todayLook: "आज तुमच्या शेताची त्वरित माहिती.",
    temperature: "तापमान",
    humidity: "आर्द्रता",
    rain: "पाऊस (48तास)",
    spoilageAlert: "खराबी सूचना",
    activeAnalyses: "सक्रिय विश्लेषण",
    priceTrend: "किंमत कल",
    recentAnalyses: "अलीकडील विश्लेषण",
    runAnalysis: "अंदाज पाहण्यासाठी विश्लेषण करा",
    startFirst: "पहिले विश्लेषण सुरू करा →",
    selectLanguage: "भाषा निवडा",
    loading: "लोड होत आहे...",
    viewAll: "सर्व पहा",
    logout: "लॉग आउट",
    friday: "शुक्रवार",
  },
  pa: {
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    newAnalysis: "ਨਵਾਂ ਵਿਸ਼ਲੇਸ਼ਣ",
    history: "ਇਤਿਹਾਸ",
    market: "ਬਾਜ਼ਾਰ",
    coldStorage: "ਠੰਡਾ ਭੰਡਾਰ",
    weather: "ਮੌਸਮ",
    govSchemes: "ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ",
    profile: "ਪ੍ਰੋਫ਼ਾਈਲ",
    settings: "ਸੈਟਿੰਗਾਂ",
    namaste: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ",
    todayLook: "ਅੱਜ ਤੁਹਾਡੇ ਖੇਤ ਦੀ ਤਤਕਾਲ ਜਾਣਕਾਰੀ।",
    temperature: "ਤਾਪਮਾਨ",
    humidity: "ਨਮੀ",
    rain: "ਮੀਂਹ (48ਘੰ)",
    spoilageAlert: "ਖਰਾਬੀ ਚੇਤਾਵਨੀ",
    activeAnalyses: "ਸਰਗਰਮ ਵਿਸ਼ਲੇਸ਼ਣ",
    priceTrend: "ਕੀਮਤ ਰੁਝਾਨ",
    recentAnalyses: "ਹਾਲੀਆ ਵਿਸ਼ਲੇਸ਼ਣ",
    runAnalysis: "ਅਨੁਮਾਨ ਦੇਖਣ ਲਈ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
    startFirst: "ਪਹਿਲਾ ਵਿਸ਼ਲੇਸ਼ਣ ਸ਼ੁਰੂ ਕਰੋ →",
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    viewAll: "ਸਭ ਦੇਖੋ",
    logout: "ਲੌਗ ਆਊਟ",
    friday: "ਸ਼ੁੱਕਰਵਾਰ",
  },
  gu: {
    dashboard: "ડૅશબોર્ડ",
    newAnalysis: "નવું વિશ્લેષણ",
    history: "ઇતિહાસ",
    market: "બજાર",
    coldStorage: "શીત ભંડાર",
    weather: "હવામાન",
    govSchemes: "સરકારી યોજનાઓ",
    profile: "પ્રોફાઇલ",
    settings: "સેટિંગ્સ",
    namaste: "નમસ્તે",
    todayLook: "આજે તમારા ખેતરની ઝડપી ઝલક.",
    temperature: "તાપમાન",
    humidity: "ભેજ",
    rain: "વરસાદ (48ક)",
    spoilageAlert: "બગાડ ચેતવણી",
    activeAnalyses: "સક્રિય વિશ્લેષણ",
    priceTrend: "ભાવ વલણ",
    recentAnalyses: "તાજેતરના વિશ્લેષણ",
    runAnalysis: "અનુમાન જોવા માટે વિશ્લેષણ ચલાવો",
    startFirst: "પ્રથમ વિશ્લેષણ શરૂ કરો →",
    selectLanguage: "ભાષા પસંદ કરો",
    loading: "લોડ થઈ રહ્યું છે...",
    viewAll: "બધું જુઓ",
    logout: "લૉગ આઉટ",
    friday: "શુક્રવાર",
  },
  bn: {
    dashboard: "ড্যাশবোর্ড",
    newAnalysis: "নতুন বিশ্লেষণ",
    history: "ইতিহাস",
    market: "বাজার",
    coldStorage: "শীতল ভাণ্ডার",
    weather: "আবহাওয়া",
    govSchemes: "সরকারি প্রকল্প",
    profile: "প্রোফাইল",
    settings: "সেটিংস",
    namaste: "নমস্কার",
    todayLook: "আজ আপনার খামারের দ্রুত দেখুন।",
    temperature: "তাপমাত্রা",
    humidity: "আর্দ্রতা",
    rain: "বৃষ্টি (৪৮ঘ)",
    spoilageAlert: "পচন সতর্কতা",
    activeAnalyses: "সক্রিয় বিশ্লেষণ",
    priceTrend: "মূল্য প্রবণতা",
    recentAnalyses: "সাম্প্রতিক বিশ্লেষণ",
    runAnalysis: "পূর্বাভাস দেখতে বিশ্লেষণ করুন",
    startFirst: "প্রথম বিশ্লেষণ শুরু করুন →",
    selectLanguage: "ভাষা নির্বাচন করুন",
    loading: "লোড হচ্ছে...",
    viewAll: "সব দেখুন",
    logout: "লগ আউট",
    friday: "শুক্রবার",
  },
  ta: {
    dashboard: "டாஷ்போர்டு",
    newAnalysis: "புதிய பகுப்பாய்வு",
    history: "வரலாறு",
    market: "சந்தை",
    coldStorage: "குளிர் சேமிப்பு",
    weather: "வானிலை",
    govSchemes: "அரசு திட்டங்கள்",
    profile: "சுயவிவரம்",
    settings: "அமைப்புகள்",
    namaste: "வணக்கம்",
    todayLook: "இன்று உங்கள் பண்ணையின் விரைவான பார்வை.",
    temperature: "வெப்பநிலை",
    humidity: "ஈரப்பதம்",
    rain: "மழை (48மணி)",
    spoilageAlert: "கெட்டுப்போகும் எச்சரிக்கை",
    activeAnalyses: "செயலில் பகுப்பாய்வு",
    priceTrend: "விலை போக்கு",
    recentAnalyses: "சமீபத்திய பகுப்பாய்வு",
    runAnalysis: "முன்னறிவிப்பைப் பார்க்க பகுப்பாய்வை இயக்கவும்",
    startFirst: "முதல் பகுப்பாய்வைத் தொடங்கவும் →",
    selectLanguage: "மொழியைத் தேர்ந்தெடு",
    loading: "ஏற்றுகிறது...",
    viewAll: "அனைத்தும் பார்",
    logout: "வெளியேறு",
    friday: "வெள்ளி",
  },
  te: {
    dashboard: "డాష్‌బోర్డ్",
    newAnalysis: "కొత్త విశ్లేషణ",
    history: "చరిత్ర",
    market: "మార్కెట్",
    coldStorage: "శీతల నిల్వ",
    weather: "వాతావరణం",
    govSchemes: "ప్రభుత్వ పథకాలు",
    profile: "ప్రొఫైల్",
    settings: "సెట్టింగ్‌లు",
    namaste: "నమస్కారం",
    todayLook: "ఈరోజు మీ వ్యవసాయ క్షేత్రం యొక్క శీఘ్ర చూపు.",
    temperature: "ఉష్ణోగ్రత",
    humidity: "తేమ",
    rain: "వర్షం (48గ)",
    spoilageAlert: "పాడవడం హెచ్చరిక",
    activeAnalyses: "క్రియాశీల విశ్లేషణ",
    priceTrend: "ధర ధోరణి",
    recentAnalyses: "ఇటీవలి విశ్లేషణలు",
    runAnalysis: "అంచనాలు చూడటానికి విశ్లేషణ నడపండి",
    startFirst: "మొదటి విశ్లేషణ ప్రారంభించండి →",
    selectLanguage: "భాష ఎంచుకోండి",
    loading: "లోడ్ అవుతోంది...",
    viewAll: "అన్నీ చూడండి",
    logout: "లాగ్ అవుట్",
    friday: "శుక్రవారం",
  },
  kn: {
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    newAnalysis: "ಹೊಸ ವಿಶ್ಲೇಷಣೆ",
    history: "ಇತಿಹಾಸ",
    market: "ಮಾರುಕಟ್ಟೆ",
    coldStorage: "ಶೀತ ಸಂಗ್ರಹ",
    weather: "ಹವಾಮಾನ",
    govSchemes: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    profile: "ಪ್ರೊಫೈಲ್",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    namaste: "ನಮಸ್ಕಾರ",
    todayLook: "ಇಂದು ನಿಮ್ಮ ಜಮೀನಿನ ತ್ವರಿತ ನೋಟ.",
    temperature: "ತಾಪಮಾನ",
    humidity: "ಆರ್ದ್ರತೆ",
    rain: "ಮಳೆ (48ಘಂ)",
    spoilageAlert: "ಕೆಡುವ ಎಚ್ಚರಿಕೆ",
    activeAnalyses: "ಸಕ್ರಿಯ ವಿಶ್ಲೇಷಣೆ",
    priceTrend: "ಬೆಲೆ ಪ್ರವೃತ್ತಿ",
    recentAnalyses: "ಇತ್ತೀಚಿನ ವಿಶ್ಲೇಷಣೆಗಳು",
    runAnalysis: "ಮುನ್ನೋಟ ನೋಡಲು ವಿಶ್ಲೇಷಣೆ ನಡೆಸಿ",
    startFirst: "ಮೊದಲ ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭಿಸಿ →",
    selectLanguage: "ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    viewAll: "ಎಲ್ಲವನ್ನು ನೋಡಿ",
    logout: "ಲಾಗ್ ಔಟ್",
    friday: "ಶುಕ್ರವಾರ",
  },
  ml: {
    dashboard: "ഡാഷ്‌ബോർഡ്",
    newAnalysis: "പുതിയ വിശകലനം",
    history: "ചരിത്രം",
    market: "മാർക്കറ്റ്",
    coldStorage: "ശീതള സംഭരണം",
    weather: "കാലാവസ്ഥ",
    govSchemes: "സർക്കാർ പദ്ധതികൾ",
    profile: "പ്രൊഫൈൽ",
    settings: "ക്രമീകരണങ്ങൾ",
    namaste: "നമസ്കാരം",
    todayLook: "ഇന്ന് നിങ്ങളുടെ ഫാമിന്റെ ഒരു ദ്രുത നോട്ടം.",
    temperature: "താപനില",
    humidity: "ആർദ്രത",
    rain: "മഴ (48മ)",
    spoilageAlert: "കേടുവരൽ മുന്നറിയിപ്പ്",
    activeAnalyses: "സജീവ വിശകലനം",
    priceTrend: "വില പ്രവണത",
    recentAnalyses: "സമീപകാല വിശകലനങ്ങൾ",
    runAnalysis: "പ്രവചനങ്ങൾ കാണാൻ വിശകലനം നടത്തുക",
    startFirst: "ആദ്യ വിശകലനം ആരംഭിക്കുക →",
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    loading: "ലോഡ് ആകുന്നു...",
    viewAll: "എല്ലാം കാണുക",
    logout: "ലോഗ് ഔട്ട്",
    friday: "വെള്ളിയാഴ്ച",
  },
  ur: {
    dashboard: "ڈیش بورڈ",
    newAnalysis: "نیا تجزیہ",
    history: "تاریخ",
    market: "بازار",
    coldStorage: "سرد ذخیرہ",
    weather: "موسم",
    govSchemes: "سرکاری منصوبے",
    profile: "پروفائل",
    settings: "ترتیبات",
    namaste: "السلام علیکم",
    todayLook: "آج آپ کے فارم کی فوری جھلک۔",
    temperature: "درجہ حرارت",
    humidity: "نمی",
    rain: "بارش (48گھ)",
    spoilageAlert: "خراب ہونے کی تنبیہ",
    activeAnalyses: "فعال تجزیے",
    priceTrend: "قیمت کا رجحان",
    recentAnalyses: "حالیہ تجزیے",
    runAnalysis: "پیش گوئی دیکھنے کے لیے تجزیہ چلائیں",
    startFirst: "پہلا تجزیہ شروع کریں →",
    selectLanguage: "زبان منتخب کریں",
    loading: "لوڈ ہو رہا ہے...",
    viewAll: "سب دیکھیں",
    logout: "لاگ آؤٹ",
    friday: "جمعہ",
  },
  or: {
    dashboard: "ଡ୍ୟାଶ୍‌ବୋର୍ଡ",
    newAnalysis: "ନୂତନ ବିଶ୍ଳେଷଣ",
    history: "ଇତିହାସ",
    market: "ବଜାର",
    coldStorage: "ଶୀତଳ ଭଣ୍ଡାର",
    weather: "ପାଣିପାଗ",
    govSchemes: "ସରକାରୀ ଯୋଜନା",
    profile: "ପ୍ରୋଫାଇଲ",
    settings: "ସେଟିଂ",
    namaste: "ନମସ୍କାର",
    todayLook: "ଆଜି ଆପଣଙ୍କ ଖେତର ଦ୍ରୁତ ଦୃଶ୍ୟ।",
    temperature: "ତାପମାତ୍ରା",
    humidity: "ଆର୍ଦ୍ରତା",
    rain: "ବର୍ଷା (48ଘ)",
    spoilageAlert: "ନଷ୍ଟ ସତର୍କତା",
    activeAnalyses: "ସକ୍ରିୟ ବିଶ୍ଳେଷଣ",
    priceTrend: "ମୂଲ୍ୟ ପ୍ରବଣତା",
    recentAnalyses: "ସଦ୍ୟ ବିଶ୍ଳେଷଣ",
    runAnalysis: "ପୂର୍ବାନୁମାନ ଦେଖିବାକୁ ବିଶ୍ଳେଷଣ କରନ୍ତୁ",
    startFirst: "ପ୍ରଥମ ବିଶ୍ଳେଷଣ ଆରମ୍ଭ କରନ୍ତୁ →",
    selectLanguage: "ଭାଷା ବାଛନ୍ତୁ",
    loading: "ଲୋଡ ହେଉଛି...",
    viewAll: "ସବୁ ଦେଖନ୍ତୁ",
    logout: "ଲଗ୍ ଆଉଟ",
    friday: "ଶୁକ୍ରବାର",
  },
};

interface LanguageContextType {
  lang: string;
  setLang: (code: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<string>(() => {
    return localStorage.getItem("fasalseva_lang") ?? "en";
  });

  const setLang = (code: string) => {
    setLangState(code);
    localStorage.setItem("fasalseva_lang", code);
    // Set HTML dir for RTL languages
    document.documentElement.dir = code === "ur" ? "rtl" : "ltr";
    document.documentElement.lang = code;
  };

  useEffect(() => {
    document.documentElement.dir = lang === "ur" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, []);

  const t = (key: string): string => {
    return translations[lang]?.[key] ?? translations["en"]?.[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}